{{- $serviceAccount := .Values.serviceAccount | default dict -}}
{{- if (default true $serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "Discovery-Agent.serviceAccountName" . }}
  labels:
    {{- include "Discovery-Agent.labels" . | nindent 4 }}
  annotations:
    {{- include "Discovery-Agent.annotations" . | nindent 4 }}
  {{- with $serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ default true $serviceAccount.automount }}
{{- end }}
